### ISSUE TITLE
Master branch supports Conjur OSS and DAP

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-api-dotnet#43]
Update the master branch to add functionality to support Conjur OSS and DAP

AC:
- [x] Update functionality
- [x] Update README to be clear about functionality, and to list supported versions of Conjur OSS and DAP

**Comment by JakeQuilty** [comment]
### Testing Functionality and Fixing Tests
https://github.com/cyberark/conjur-api-dotnet/pull/44
https://github.com/cyberark/conjur-api-dotnet/issues/41

### PR to Merge into master
https://github.com/cyberark/conjur-api-dotnet/pull/48

**Comment by sgnn7** [comment]
Resolves #2
