### ISSUE TITLE
Use Windows credentials or Service credentials for client

### ISSUE THREAD

**Issue by ashish4github** [cyberark/conjur-api-dotnet#72]
Is there a way to access secrets form a dotnet client using the identity of the service under which code is running e.g. Windows Service or an API running in Kestrel/IIS under a service account?

Alternatively, can a machine  be authenticated for access to secrets?

**Comment by doodlesbykumbi** [comment]
Hi @ashish4github. Thanks for creating the issue. All Conjur clients make use of identity based on some authenticator that Conjur supports. [Azure](https://docs.conjur.org/Latest/en/Content/Operations/Services/azure_authn.htm) and [LDAP](https://docs.conjur.org/Latest/en/Content/Integrations/ldap/ldap-sync-authn-integration.htm?tocpath=Integrations%7CLDAP%20Authentication%7C_____1) authenticators make sense in the context of Windows so perhaps those might be what you are looking for.

To the best of my knowledge Conjur does not have an authenticator that establishes identity based on machine-local identity on Windows, such as a service account etc.
